# Generated by Django 5.2.8 on 2026-08-20 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0006_savedpaymentmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('paystack', 'Card / Bank (Paystack)'), ('cash_on_delivery', 'Cash on Delivery'), ('bank_transfer', 'Bank Transfer')], default='paystack', max_length=32),
        ),
    ]
