# Generated by Django 5.2.8 on 2026-08-20 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0007_payment_method_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='A M TECH SOLUTIONS', max_length=120)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('support_phone', models.CharField(blank=True, max_length=30)),
                ('twitter_handle', models.CharField(blank=True, help_text='Without @', max_length=60)),
                ('facebook_handle', models.CharField(blank=True, help_text='Username or page slug', max_length=60)),
                ('instagram_handle', models.CharField(blank=True, help_text='Without @', max_length=60)),
                ('linkedin_handle', models.CharField(blank=True, help_text='Username or page slug', max_length=60)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site setting',
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
