# Generated by Django 5.2.8 on 2026-08-20 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0008_site_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='bank_instructions',
            field=models.TextField(blank=True, help_text='Instructions shown to customers during bank transfer checkout'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='bank_name',
            field=models.CharField(blank=True, help_text='e.g. GTBank', max_length=120),
        ),
    ]
